# Read the text file storing the PC matrix---that is, the projection
# of the genotype samples onto k PCs---generated by the MATLAB script
# geno_pca.m.
read.pcs <- function (filename)
  read.table(filename,header = TRUE,stringsAsFactors = FALSE)

# TO DO: Explain what this function does.
plotpca <- function () {

}
